# Generated by Django 3.2.9 on 2022-01-08 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flux', '0004_alter_review_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='is_reviewed',
            field=models.BooleanField(default=False),
        ),
    ]
