# Generated by Django 3.2.9 on 2022-01-04 09:08

from django.db import migrations

def create_groups(apps, schema_migration):
    User = apps.get_model('authentication', 'User')
    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')
    
    create_review = Permission.objects.get(codename='create_review')
    create_ticket = Permission.objects.get(codename='create_ticket')
    edit_review = Permission.objects.get(codename='edit_ticket')
    edit_ticket = Permission.objects.get(codename='edit_review')
    create_review_ticket = Permission.objects.get(codename='create_review_ticket')


    author_permissions = [
        create_review,
        create_ticket,
        edit_review,
        edit_ticket,
        create_review_ticket
    ]
    
    authors = Group(name='authors')
    authors.save()
    authors.permissions.set(author_permissions)

    followers = Group(name='followers')
    followers.save()
    followers.permissions.add(flux)
    
    for user in User.objects.all():
        if user.role == 'AUTHOR':
            authors.user_set.add(user)
        if user.role == 'FOLLOWER':
            followers.user_set.add(user)


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_groups)
    ]


